# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
platform :ios, '15.0'
target 'TwitterCloneProject' do
  # Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
	inhibit_all_warnings!

  # Pods for TwitterCloneProject
		
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'SDWebImage', '~> 5.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end

end
